/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Options for the cx-package builder
 */
export interface CxPackageBuilderOptions {
  /**
   * Output directory where the zip will be generated
   */
  destDir?: string;
  /**
   * File name of the generated zip
   */
  destFileName?: string;
  /**
   * List of items to bundle in in the package zip
   */
  items: [
    {
      type: "page";
      name: string;
    },
    ...{
      type: "page";
      name: string;
    }[]
  ];
}
